field: fd0c8e02-99b4-4ce5-ab89-b29cd0efc581 # Content Builder
fieldLayouts:
  29091f1e-ecb0-44d5-83e5-0449d42dfc50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cfa9b9fb-13ac-48d4-9525-d51caed66583 # Brow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8e83ab2-17c9-4901-824c-d4b2857d0f22
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 70842856-8b10-4b22-ac3d-e127825aca24 # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1c1fcc6-05a9-4a12-aebd-2b632568c450
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54de1c1c-79d6-40ed-911b-422f630094e1 # Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7b57110-500a-43ca-aa57-b89842e7ffeb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f294926b-0b7b-470e-8e62-bfeea6be010b # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fc1158a-a3b9-49bc-9330-79ea406d857a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40ec5343-f083-489f-a6eb-49ff9ee6d600 # Use Image as Background?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 301f4d2c-64a7-4a64-adba-a08dd3071d01
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a3aa486f-473f-4b4d-b3ae-808963595c58 # Text Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 994eb38c-d7fa-43e0-aabb-b9000ff369a7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8ed0d9cb-1498-4dbd-b451-573a77710798 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 483edeb0-be9d-4600-aafd-2de83e2e2050
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a081fc5f-03ce-4909-8255-dd92e7c9076c # Call to Action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f272a050-0c75-43fd-933c-0855afcd778f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cbd3e545-f350-4073-b3a6-6c86e43dd287
        userCondition: null
fields:
  8ed0d9cb-1498-4dbd-b451-573a77710798: # Background Color
    columnSuffix: ccgsctma
    contentColumnType: text
    fieldGroup: null
    handle: backgroundColor
    instructions: 'Select a background color for this section.'
    name: 'Background Color'
    searchable: false
    settings:
      default: null
      palette: 'Spotlight Backgrounds'
      setRandom: false
      useConfigFile: true
    translationKeyFormat: null
    translationMethod: none
    type: percipiolondon\colourswatches\fields\ColourSwatches
  40ec5343-f083-489f-a6eb-49ff9ee6d600: # Use Image as Background?
    columnSuffix: qjfuiqbu
    contentColumnType: boolean
    fieldGroup: null
    handle: useImageAsBackground
    instructions: 'If enabled, the spotlight image will be used as a background image instead of being shown to the side.'
    name: 'Use Image as Background?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  54de1c1c-79d6-40ed-911b-422f630094e1: # Description
    columnSuffix: llsqgbsx
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: 'Enter summary content. On mobile, the image will appear above the description, so avoid referring to the image’s position in the text.'
    name: Description
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      ckeConfig: c612c6ea-c3d2-478c-884d-38e79c269c32 # Simple With Links
      columnType: text
      defaultTransform: ''
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  70842856-8b10-4b22-ac3d-e127825aca24: # Heading
    columnSuffix: yltyilio
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a081fc5f-03ce-4909-8255-dd92e7c9076c: # Call to Action
    columnSuffix: rilqaebz
    contentColumnType: text
    fieldGroup: null
    handle: callToAction
    instructions: 'Add a button at the bottom of your spotlight that can link out to other content.'
    name: 'Call to Action'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
                -
                  - allowAlias
                  - '1'
                -
                  - allowMailto
                  - '1'
                -
                  - allowHash
                  - '1'
                -
                  - allowPaths
                  - '1'
          -
            - presseddigital\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'section:fb3b532b-07c0-4cc1-a0ea-a2b75a26cc8f' # Boards & Commissions
                    - 'section:b3411cb1-e860-46ed-9cd6-58cf9b8daacb' # Departments
                    - 'section:9da43fd8-c505-4d19-9486-e0cb669c568a' # Document Packets
                    - 'section:8b7c4e26-9aab-4c5d-874e-aee151107de3' # Documents
                    - 'section:9db08bfd-737a-4544-a641-4c138f2b3b0a' # Events
                    - 'section:86dfc275-b48e-44d4-8c8c-acda592d92b0' # Meetings
                    - 'section:983c9f6f-9251-4fd3-91e1-b598eccc6a1a' # News
                    - 'section:28881fc8-3e61-4fdb-a5ee-cce1bab725bf' # Officials
                    - 'section:98d541ae-56ee-4c98-ba9c-37438dc485a0' # Projects
                    - 'section:24fa116b-8516-4626-84f3-86b685e71071' # Resources
                    - 'section:b7e437e1-239f-4c5c-8c62-5f0323f9d22c' # Services
                    - singles
                    - 'section:07faad04-9ec4-4f68-9fe8-0ca20f189f8a' # Staff
                    - 'section:fbf8b9b0-8875-4e08-819a-d62603676dc4' # Teams
                    - 'section:70778563-6dac-453d-a4b0-5121f3a614b7' # Topics
                    - 'section:17d5d48d-2d75-4742-8820-cdce13764482' # Volunteers
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
  a3aa486f-473f-4b4d-b3ae-808963595c58: # Text Position
    columnSuffix: lpbivgdt
    contentColumnType: boolean
    fieldGroup: null
    handle: alignment
    instructions: 'Choose which side the text appears on desktop layouts. On mobile layouts it will appear below the image, if shown.'
    name: 'Text Position'
    searchable: false
    settings:
      default: false
      offLabel: Left
      onLabel: Right
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  cfa9b9fb-13ac-48d4-9525-d51caed66583: # Brow
    columnSuffix: fnatkbow
    contentColumnType: text
    fieldGroup: null
    handle: brow
    instructions: 'Will default to ‘Spotlight’. Customize if needed.'
    name: Brow
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f294926b-0b7b-470e-8e62-bfeea6be010b: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'Choose an image that will be displayed to the side of the text on desktop.'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:549d1a55-e94b-4c89-9cb9-b1fdac9d417d' # General Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:8319fc25-f6c3-449d-a648-e891478b31a6' # Icons
      restrictedLocationSubpath: null
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: true
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: spotlight
name: Spotlight
sortOrder: 33
