field: fd0c8e02-99b4-4ce5-ab89-b29cd0efc581 # Content Builder
fieldLayouts:
  00d2d434-9858-470b-9311-b6b27dc6fd06:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bde3bd63-a118-435a-b947-3f2667918e1b # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c505f40c-ff66-451e-a7a3-777b81eec3de
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bcbcc37a-a53b-42f8-9a80-e9abf9ffe063 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7461afe4-a16b-46eb-9118-abef94cf409a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d0cf7d52-44a5-44a7-9efa-ba27c7541ff9 # Image Column Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e893b7d-90eb-4761-aed1-fff5a3e04794
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e58f615b-174a-4196-a96c-e824862acfa9 # Image Column Width
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12e1a8fb-7264-441b-908f-fac4e69efccd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 323dd893-cdef-4562-9cfc-566d7afd7909 # Text Block
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08141f06-e88b-4575-bf8e-db7807c52ed8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 566d26c2-9af4-45bb-b994-a552cc3fc03b # Display Alt Text as Caption?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6efb1a5-c13d-4f3c-8073-1e22fc815e36
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c8061611-d9e5-4ee6-b698-dc19feb2e2a5 # Call to Action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9874e73-2e67-48dc-a8c7-cca0b8c03e8e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f36e253-5eb9-4a32-8f21-252168c2539d
        userCondition: null
fields:
  323dd893-cdef-4562-9cfc-566d7afd7909: # Text Block
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: textBlock
    instructions: 'Enter your text content here. Remember that the image will appear to the top of the text regardless of its position on desktop, so avoid referring to the image’s position in the text.'
    name: 'Text Block'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: 'Basic with Links.json'
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  566d26c2-9af4-45bb-b994-a552cc3fc03b: # Display Alt Text as Caption?
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: displayAltTextAsCaption
    instructions: 'If enabled, this will display your image''s alt text as a small figure caption below the image.'
    name: 'Display Alt Text as Caption?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  bcbcc37a-a53b-42f8-9a80-e9abf9ffe063: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'Choose an image to display to the side of the text.'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:549d1a55-e94b-4c89-9cb9-b1fdac9d417d' # General Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:549d1a55-e94b-4c89-9cb9-b1fdac9d417d' # General Images
      restrictedLocationSubpath: null
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: true
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  bde3bd63-a118-435a-b947-3f2667918e1b: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c8061611-d9e5-4ee6-b698-dc19feb2e2a5: # Call to Action
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: callToAction
    instructions: 'Adds a button link at the bottom of your text that can link out to other content'
    name: 'Call to Action'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - dotgovsupport@oaklandca.gov
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - 'https://www.oaklandca.gov'
                -
                  - allowAlias
                  - ''
                -
                  - allowMailto
                  - ''
                -
                  - allowHash
                  - ''
                -
                  - allowPaths
                  - ''
          -
            - presseddigital\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - '["section:fb3b532b-07c0-4cc1-a0ea-a2b75a26cc8f","section:b3411cb1-e860-46ed-9cd6-58cf9b8daacb","section:9da43fd8-c505-4d19-9486-e0cb669c568a","section:8b7c4e26-9aab-4c5d-874e-aee151107de3","section:983c9f6f-9251-4fd3-91e1-b598eccc6a1a","section:28881fc8-3e61-4fdb-a5ee-cce1bab725bf","section:be8acece-2031-4965-a62f-31911d00e24c","section:98d541ae-56ee-4c98-ba9c-37438dc485a0","section:24fa116b-8516-4626-84f3-86b685e71071","section:b7e437e1-239f-4c5c-8c62-5f0323f9d22c","section:70778563-6dac-453d-a4b0-5121f3a614b7"]' # Documents # Document Packets # Resources # Projects # News # Officials # Topics # Services # Departments # Boards & Commissions
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'section:fb3b532b-07c0-4cc1-a0ea-a2b75a26cc8f' # Boards & Commissions
                    - 'section:b3411cb1-e860-46ed-9cd6-58cf9b8daacb' # Departments
                    - 'section:9da43fd8-c505-4d19-9486-e0cb669c568a' # Document Packets
                    - 'section:8b7c4e26-9aab-4c5d-874e-aee151107de3' # Documents
                    - 'section:983c9f6f-9251-4fd3-91e1-b598eccc6a1a' # News
                    - 'section:28881fc8-3e61-4fdb-a5ee-cce1bab725bf' # Officials
                    - 'section:98d541ae-56ee-4c98-ba9c-37438dc485a0' # Projects
                    - 'section:24fa116b-8516-4626-84f3-86b685e71071' # Resources
                    - 'section:b7e437e1-239f-4c5c-8c62-5f0323f9d22c' # Services
                    - 'section:70778563-6dac-453d-a4b0-5121f3a614b7' # Topics
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'folder:baf733c3-48be-42a7-8b4f-7a6bf9763542'
                -
                  - customSelectionLabel
                  - 'Select Document'
          -
            - presseddigital\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
  d0cf7d52-44a5-44a7-9efa-ba27c7541ff9: # Image Column Position
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageColumnPosition
    instructions: 'Choose which side the image appears on desktop layouts. On mobile layouts it will appear above the text, so make sure you don’t refer to the image’s position in your text block.'
    name: 'Image Column Position'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  e58f615b-174a-4196-a96c-e824862acfa9: # Image Column Width
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageColumnWidth
    instructions: 'Choose a width for the image column on tablet and desktop browsers. On mobile layouts it will be 100% of the browser width.'
    name: 'Image Column Width'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 25%
            -
              - value
              - 1/4
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 33%
            -
              - value
              - 1/3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 50%
            -
              - value
              - 1/2
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: textImageBlock
name: 'Text & Image Block'
sortOrder: 4
